/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gandhir' at '1/8/17 6:55 PM' with Gradle 3.0
 *
 * @author gandhir, @date 1/8/17 6:55 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
